### PR TITLE
Add a flag to hide all channels

### PR DESCRIPTION
**Pull request by WhoSayIn**
I barely watch the TV channels but right now a huge list of them is loading no matter what.

So I added a new parameter; `CONF_HIDE_CHANNELS`. Not the most beautiful solution, I know.

I was thinking about combining this with `CONF_FAV_ONLY` and come up with a generic parameter like the following, but also wanted to keep backward compatibility.

`CONF_CHANNELS = SHOW_ALL | FAV_ONLY | HIDE_ALL`

What do you think?

### CODE REVIEW

**Comment by nstrelow** [comment]
Nice change, thanks a lot!

I really like your second idea with the SHOW_ALL and more. Is there a standard way of doing 3 part options? Anyway, definitely a good idea!

We can merge this, so people can use it. Maybe add the better option in the future then.

**Comment by WhoSayIn** [comment]
Would be fairly easy to add an `enum` config parameter. `voluptuous` has a feature for that. Should be something roughly like;

```
   vol.Required(CONF_CHANNELS): vol.In(
       ("SHOW_ALL", "FAV_ONLY", "HIDE_ALL")
   )
```

I'll implement the feature once I got the time.

**Comment by WhoSayIn** [comment]
I have some other ideas as well and not sure at this point if it would make sense to have it as a separate project or rewrite this one. 

Jointspace API has a lot of features which we can expose and use them in a custom card. Such as a complete functional remote, with arrow keys, controlling the ambilight etc.

**Comment by nstrelow** [comment]
Pretty nice, what additional functionality are you talking about?
Via keys a looooot is possible ^^

I used to discuss a lot of possible ways to interact via the v6 joinspace API here:
https://github.com/suborb/philips_android_tv/issues

**Pull request merged**
